swagger: "2.0"
info:
  description: Something about the API
  version: "1.0.0"
  title: My Cool API
basePath: "/api/v1"
schemes:
  - "https"
paths:
  /ping:
    get:
      tags:
        - "root"
      summary: "Get Server Information"
      operationId: "ping"
      produces:
      - "application/json"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ServerInfo"
definitions:
  ServerInfo:
    type: "object"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      version:
        type: "string"
      uptime:
        type: "number"
